name             'prague'
maintainer       'ControlShift Labs'
maintainer_email 'systems@controlshiftlabs.com'
license          'All rights reserved'
description      'Installs/Configures a dev env for prague-server'
long_description  'Installs/Configures a dev env for prague-server'
version          '0.0.1'

depends   'apt'
depends   'postgresql'
depends   'redisio'